/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/member'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportMembersRouteImport } from './routes/report.members'
import { Route as ReportFinancialRouteImport } from './routes/report.financial'
import { Route as ReportEventsRouteImport } from './routes/report.events'
import { Route as ReportContributionsRouteImport } from './routes/report.contributions'
import { Route as ReportCashFlowRouteImport } from './routes/report.cash-flow'
import { Route as ReportAssistanceRouteImport } from './routes/report.assistance'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberDashboardRouteImport } from './routes/member.dashboard'
import { Route as MemberContributionsRouteImport } from './routes/member.contributions'
import { Route as MemberAssistanceRouteImport } from './routes/member.assistance'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ShellStaffRouteImport } from './routes/_shell.staff'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSearchRouteImport } from './routes/_shell.search'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellMembersRouteImport } from './routes/_shell.members'
import { Route as ShellFinancialsRouteImport } from './routes/_shell.financials'
import { Route as ShellDocumentsRouteImport } from './routes/_shell.documents'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellContributionsRouteImport } from './routes/_shell.contributions'
import { Route as ShellCollectionEventsRouteImport } from './routes/_shell.collection-events'
import { Route as ShellAuditRouteImport } from './routes/_shell.audit'
import { Route as ShellAssistanceRouteImport } from './routes/_shell.assistance'
import { Route as ShellAnnouncementsRouteImport } from './routes/_shell.announcements'
import { Route as ShellStaffIdRouteImport } from './routes/_shell.staff.$id'
import { Route as ShellMembersNewRouteImport } from './routes/_shell.members.new'
import { Route as ShellMembersIdRouteImport } from './routes/_shell.members.$id'
import { Route as ShellContributionsNewRouteImport } from './routes/_shell.contributions.new'
import { Route as ShellCollectionEventsIdRouteImport } from './routes/_shell.collection-events.$id'
import { Route as ShellAssistanceNewRouteImport } from './routes/_shell.assistance.new'
import { Route as ShellAnnouncementsNewRouteImport } from './routes/_shell.announcements.new'

const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportMembersRoute = ReportMembersRouteImport.update({
  id: '/report/members',
  path: '/report/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFinancialRoute = ReportFinancialRouteImport.update({
  id: '/report/financial',
  path: '/report/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportEventsRoute = ReportEventsRouteImport.update({
  id: '/report/events',
  path: '/report/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportContributionsRoute = ReportContributionsRouteImport.update({
  id: '/report/contributions',
  path: '/report/contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCashFlowRoute = ReportCashFlowRouteImport.update({
  id: '/report/cash-flow',
  path: '/report/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAssistanceRoute = ReportAssistanceRouteImport.update({
  id: '/report/assistance',
  path: '/report/assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MemberRoute,
} as any)
const MemberContributionsRoute = MemberContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => MemberRoute,
} as any)
const MemberAssistanceRoute = MemberAssistanceRouteImport.update({
  id: '/assistance',
  path: '/assistance',
  getParentRoute: () => MemberRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ShellStaffRoute = ShellStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSearchRoute = ShellSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMembersRoute = ShellMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFinancialsRoute = ShellFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContributionsRoute = ShellContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCollectionEventsRoute = ShellCollectionEventsRouteImport.update({
  id: '/collection-events',
  path: '/collection-events',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditRoute = ShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssistanceRoute = ShellAssistanceRouteImport.update({
  id: '/assistance',
  path: '/assistance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnnouncementsRoute = ShellAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStaffIdRoute = ShellStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellStaffRoute,
} as any)
const ShellMembersNewRoute = ShellMembersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShellMembersRoute,
} as any)
const ShellMembersIdRoute = ShellMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellMembersRoute,
} as any)
const ShellContributionsNewRoute = ShellContributionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShellContributionsRoute,
} as any)
const ShellCollectionEventsIdRoute = ShellCollectionEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellCollectionEventsRoute,
} as any)
const ShellAssistanceNewRoute = ShellAssistanceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShellAssistanceRoute,
} as any)
const ShellAnnouncementsNewRoute = ShellAnnouncementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShellAnnouncementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/maintenance': typeof MaintenanceRoute
  '/member': typeof MemberRouteWithChildren
  '/announcements': typeof ShellAnnouncementsRouteWithChildren
  '/assistance': typeof ShellAssistanceRouteWithChildren
  '/audit': typeof ShellAuditRoute
  '/collection-events': typeof ShellCollectionEventsRouteWithChildren
  '/contributions': typeof ShellContributionsRouteWithChildren
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRoute
  '/financials': typeof ShellFinancialsRoute
  '/members': typeof ShellMembersRouteWithChildren
  '/notifications': typeof ShellNotificationsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/search': typeof ShellSearchRoute
  '/settings': typeof ShellSettingsRoute
  '/staff': typeof ShellStaffRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/member/assistance': typeof MemberAssistanceRoute
  '/member/contributions': typeof MemberContributionsRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/profile': typeof MemberProfileRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/report/assistance': typeof ReportAssistanceRoute
  '/report/cash-flow': typeof ReportCashFlowRoute
  '/report/contributions': typeof ReportContributionsRoute
  '/report/events': typeof ReportEventsRoute
  '/report/financial': typeof ReportFinancialRoute
  '/report/members': typeof ReportMembersRoute
  '/announcements/new': typeof ShellAnnouncementsNewRoute
  '/assistance/new': typeof ShellAssistanceNewRoute
  '/collection-events/$id': typeof ShellCollectionEventsIdRoute
  '/contributions/new': typeof ShellContributionsNewRoute
  '/members/$id': typeof ShellMembersIdRoute
  '/members/new': typeof ShellMembersNewRoute
  '/staff/$id': typeof ShellStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/maintenance': typeof MaintenanceRoute
  '/member': typeof MemberRouteWithChildren
  '/announcements': typeof ShellAnnouncementsRouteWithChildren
  '/assistance': typeof ShellAssistanceRouteWithChildren
  '/audit': typeof ShellAuditRoute
  '/collection-events': typeof ShellCollectionEventsRouteWithChildren
  '/contributions': typeof ShellContributionsRouteWithChildren
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRoute
  '/financials': typeof ShellFinancialsRoute
  '/members': typeof ShellMembersRouteWithChildren
  '/notifications': typeof ShellNotificationsRoute
  '/profile': typeof ShellProfileRoute
  '/reports': typeof ShellReportsRoute
  '/search': typeof ShellSearchRoute
  '/settings': typeof ShellSettingsRoute
  '/staff': typeof ShellStaffRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/member/assistance': typeof MemberAssistanceRoute
  '/member/contributions': typeof MemberContributionsRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/profile': typeof MemberProfileRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/report/assistance': typeof ReportAssistanceRoute
  '/report/cash-flow': typeof ReportCashFlowRoute
  '/report/contributions': typeof ReportContributionsRoute
  '/report/events': typeof ReportEventsRoute
  '/report/financial': typeof ReportFinancialRoute
  '/report/members': typeof ReportMembersRoute
  '/announcements/new': typeof ShellAnnouncementsNewRoute
  '/assistance/new': typeof ShellAssistanceNewRoute
  '/collection-events/$id': typeof ShellCollectionEventsIdRoute
  '/contributions/new': typeof ShellContributionsNewRoute
  '/members/$id': typeof ShellMembersIdRoute
  '/members/new': typeof ShellMembersNewRoute
  '/staff/$id': typeof ShellStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/maintenance': typeof MaintenanceRoute
  '/member': typeof MemberRouteWithChildren
  '/_shell/announcements': typeof ShellAnnouncementsRouteWithChildren
  '/_shell/assistance': typeof ShellAssistanceRouteWithChildren
  '/_shell/audit': typeof ShellAuditRoute
  '/_shell/collection-events': typeof ShellCollectionEventsRouteWithChildren
  '/_shell/contributions': typeof ShellContributionsRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/documents': typeof ShellDocumentsRoute
  '/_shell/financials': typeof ShellFinancialsRoute
  '/_shell/members': typeof ShellMembersRouteWithChildren
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/search': typeof ShellSearchRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/staff': typeof ShellStaffRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/member/assistance': typeof MemberAssistanceRoute
  '/member/contributions': typeof MemberContributionsRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/profile': typeof MemberProfileRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/report/assistance': typeof ReportAssistanceRoute
  '/report/cash-flow': typeof ReportCashFlowRoute
  '/report/contributions': typeof ReportContributionsRoute
  '/report/events': typeof ReportEventsRoute
  '/report/financial': typeof ReportFinancialRoute
  '/report/members': typeof ReportMembersRoute
  '/_shell/announcements/new': typeof ShellAnnouncementsNewRoute
  '/_shell/assistance/new': typeof ShellAssistanceNewRoute
  '/_shell/collection-events/$id': typeof ShellCollectionEventsIdRoute
  '/_shell/contributions/new': typeof ShellContributionsNewRoute
  '/_shell/members/$id': typeof ShellMembersIdRoute
  '/_shell/members/new': typeof ShellMembersNewRoute
  '/_shell/staff/$id': typeof ShellStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/forbidden'
    | '/maintenance'
    | '/member'
    | '/announcements'
    | '/assistance'
    | '/audit'
    | '/collection-events'
    | '/contributions'
    | '/dashboard'
    | '/documents'
    | '/financials'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/search'
    | '/settings'
    | '/staff'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/member/assistance'
    | '/member/contributions'
    | '/member/dashboard'
    | '/member/profile'
    | '/receipt/$id'
    | '/report/assistance'
    | '/report/cash-flow'
    | '/report/contributions'
    | '/report/events'
    | '/report/financial'
    | '/report/members'
    | '/announcements/new'
    | '/assistance/new'
    | '/collection-events/$id'
    | '/contributions/new'
    | '/members/$id'
    | '/members/new'
    | '/staff/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/forbidden'
    | '/maintenance'
    | '/member'
    | '/announcements'
    | '/assistance'
    | '/audit'
    | '/collection-events'
    | '/contributions'
    | '/dashboard'
    | '/documents'
    | '/financials'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/search'
    | '/settings'
    | '/staff'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/member/assistance'
    | '/member/contributions'
    | '/member/dashboard'
    | '/member/profile'
    | '/receipt/$id'
    | '/report/assistance'
    | '/report/cash-flow'
    | '/report/contributions'
    | '/report/events'
    | '/report/financial'
    | '/report/members'
    | '/announcements/new'
    | '/assistance/new'
    | '/collection-events/$id'
    | '/contributions/new'
    | '/members/$id'
    | '/members/new'
    | '/staff/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_shell'
    | '/auth'
    | '/forbidden'
    | '/maintenance'
    | '/member'
    | '/_shell/announcements'
    | '/_shell/assistance'
    | '/_shell/audit'
    | '/_shell/collection-events'
    | '/_shell/contributions'
    | '/_shell/dashboard'
    | '/_shell/documents'
    | '/_shell/financials'
    | '/_shell/members'
    | '/_shell/notifications'
    | '/_shell/profile'
    | '/_shell/reports'
    | '/_shell/search'
    | '/_shell/settings'
    | '/_shell/staff'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/member/assistance'
    | '/member/contributions'
    | '/member/dashboard'
    | '/member/profile'
    | '/receipt/$id'
    | '/report/assistance'
    | '/report/cash-flow'
    | '/report/contributions'
    | '/report/events'
    | '/report/financial'
    | '/report/members'
    | '/_shell/announcements/new'
    | '/_shell/assistance/new'
    | '/_shell/collection-events/$id'
    | '/_shell/contributions/new'
    | '/_shell/members/$id'
    | '/_shell/members/new'
    | '/_shell/staff/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MemberRoute: typeof MemberRouteWithChildren
  ReceiptIdRoute: typeof ReceiptIdRoute
  ReportAssistanceRoute: typeof ReportAssistanceRoute
  ReportCashFlowRoute: typeof ReportCashFlowRoute
  ReportContributionsRoute: typeof ReportContributionsRoute
  ReportEventsRoute: typeof ReportEventsRoute
  ReportFinancialRoute: typeof ReportFinancialRoute
  ReportMembersRoute: typeof ReportMembersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/members': {
      id: '/report/members'
      path: '/report/members'
      fullPath: '/report/members'
      preLoaderRoute: typeof ReportMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/financial': {
      id: '/report/financial'
      path: '/report/financial'
      fullPath: '/report/financial'
      preLoaderRoute: typeof ReportFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/events': {
      id: '/report/events'
      path: '/report/events'
      fullPath: '/report/events'
      preLoaderRoute: typeof ReportEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/contributions': {
      id: '/report/contributions'
      path: '/report/contributions'
      fullPath: '/report/contributions'
      preLoaderRoute: typeof ReportContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/cash-flow': {
      id: '/report/cash-flow'
      path: '/report/cash-flow'
      fullPath: '/report/cash-flow'
      preLoaderRoute: typeof ReportCashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/assistance': {
      id: '/report/assistance'
      path: '/report/assistance'
      fullPath: '/report/assistance'
      preLoaderRoute: typeof ReportAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/dashboard': {
      id: '/member/dashboard'
      path: '/dashboard'
      fullPath: '/member/dashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/contributions': {
      id: '/member/contributions'
      path: '/contributions'
      fullPath: '/member/contributions'
      preLoaderRoute: typeof MemberContributionsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/assistance': {
      id: '/member/assistance'
      path: '/assistance'
      fullPath: '/member/assistance'
      preLoaderRoute: typeof MemberAssistanceRouteImport
      parentRoute: typeof MemberRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_shell/staff': {
      id: '/_shell/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof ShellStaffRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/search': {
      id: '/_shell/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShellSearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/members': {
      id: '/_shell/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof ShellMembersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/financials': {
      id: '/_shell/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof ShellFinancialsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contributions': {
      id: '/_shell/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof ShellContributionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/collection-events': {
      id: '/_shell/collection-events'
      path: '/collection-events'
      fullPath: '/collection-events'
      preLoaderRoute: typeof ShellCollectionEventsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit': {
      id: '/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ShellAuditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assistance': {
      id: '/_shell/assistance'
      path: '/assistance'
      fullPath: '/assistance'
      preLoaderRoute: typeof ShellAssistanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/announcements': {
      id: '/_shell/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof ShellAnnouncementsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/staff/$id': {
      id: '/_shell/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof ShellStaffIdRouteImport
      parentRoute: typeof ShellStaffRoute
    }
    '/_shell/members/new': {
      id: '/_shell/members/new'
      path: '/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof ShellMembersNewRouteImport
      parentRoute: typeof ShellMembersRoute
    }
    '/_shell/members/$id': {
      id: '/_shell/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof ShellMembersIdRouteImport
      parentRoute: typeof ShellMembersRoute
    }
    '/_shell/contributions/new': {
      id: '/_shell/contributions/new'
      path: '/new'
      fullPath: '/contributions/new'
      preLoaderRoute: typeof ShellContributionsNewRouteImport
      parentRoute: typeof ShellContributionsRoute
    }
    '/_shell/collection-events/$id': {
      id: '/_shell/collection-events/$id'
      path: '/$id'
      fullPath: '/collection-events/$id'
      preLoaderRoute: typeof ShellCollectionEventsIdRouteImport
      parentRoute: typeof ShellCollectionEventsRoute
    }
    '/_shell/assistance/new': {
      id: '/_shell/assistance/new'
      path: '/new'
      fullPath: '/assistance/new'
      preLoaderRoute: typeof ShellAssistanceNewRouteImport
      parentRoute: typeof ShellAssistanceRoute
    }
    '/_shell/announcements/new': {
      id: '/_shell/announcements/new'
      path: '/new'
      fullPath: '/announcements/new'
      preLoaderRoute: typeof ShellAnnouncementsNewRouteImport
      parentRoute: typeof ShellAnnouncementsRoute
    }
  }
}

interface ShellAnnouncementsRouteChildren {
  ShellAnnouncementsNewRoute: typeof ShellAnnouncementsNewRoute
}

const ShellAnnouncementsRouteChildren: ShellAnnouncementsRouteChildren = {
  ShellAnnouncementsNewRoute: ShellAnnouncementsNewRoute,
}

const ShellAnnouncementsRouteWithChildren =
  ShellAnnouncementsRoute._addFileChildren(ShellAnnouncementsRouteChildren)

interface ShellAssistanceRouteChildren {
  ShellAssistanceNewRoute: typeof ShellAssistanceNewRoute
}

const ShellAssistanceRouteChildren: ShellAssistanceRouteChildren = {
  ShellAssistanceNewRoute: ShellAssistanceNewRoute,
}

const ShellAssistanceRouteWithChildren = ShellAssistanceRoute._addFileChildren(
  ShellAssistanceRouteChildren,
)

interface ShellCollectionEventsRouteChildren {
  ShellCollectionEventsIdRoute: typeof ShellCollectionEventsIdRoute
}

const ShellCollectionEventsRouteChildren: ShellCollectionEventsRouteChildren = {
  ShellCollectionEventsIdRoute: ShellCollectionEventsIdRoute,
}

const ShellCollectionEventsRouteWithChildren =
  ShellCollectionEventsRoute._addFileChildren(
    ShellCollectionEventsRouteChildren,
  )

interface ShellContributionsRouteChildren {
  ShellContributionsNewRoute: typeof ShellContributionsNewRoute
}

const ShellContributionsRouteChildren: ShellContributionsRouteChildren = {
  ShellContributionsNewRoute: ShellContributionsNewRoute,
}

const ShellContributionsRouteWithChildren =
  ShellContributionsRoute._addFileChildren(ShellContributionsRouteChildren)

interface ShellMembersRouteChildren {
  ShellMembersIdRoute: typeof ShellMembersIdRoute
  ShellMembersNewRoute: typeof ShellMembersNewRoute
}

const ShellMembersRouteChildren: ShellMembersRouteChildren = {
  ShellMembersIdRoute: ShellMembersIdRoute,
  ShellMembersNewRoute: ShellMembersNewRoute,
}

const ShellMembersRouteWithChildren = ShellMembersRoute._addFileChildren(
  ShellMembersRouteChildren,
)

interface ShellStaffRouteChildren {
  ShellStaffIdRoute: typeof ShellStaffIdRoute
}

const ShellStaffRouteChildren: ShellStaffRouteChildren = {
  ShellStaffIdRoute: ShellStaffIdRoute,
}

const ShellStaffRouteWithChildren = ShellStaffRoute._addFileChildren(
  ShellStaffRouteChildren,
)

interface ShellRouteChildren {
  ShellAnnouncementsRoute: typeof ShellAnnouncementsRouteWithChildren
  ShellAssistanceRoute: typeof ShellAssistanceRouteWithChildren
  ShellAuditRoute: typeof ShellAuditRoute
  ShellCollectionEventsRoute: typeof ShellCollectionEventsRouteWithChildren
  ShellContributionsRoute: typeof ShellContributionsRouteWithChildren
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDocumentsRoute: typeof ShellDocumentsRoute
  ShellFinancialsRoute: typeof ShellFinancialsRoute
  ShellMembersRoute: typeof ShellMembersRouteWithChildren
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSearchRoute: typeof ShellSearchRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellStaffRoute: typeof ShellStaffRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnnouncementsRoute: ShellAnnouncementsRouteWithChildren,
  ShellAssistanceRoute: ShellAssistanceRouteWithChildren,
  ShellAuditRoute: ShellAuditRoute,
  ShellCollectionEventsRoute: ShellCollectionEventsRouteWithChildren,
  ShellContributionsRoute: ShellContributionsRouteWithChildren,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDocumentsRoute: ShellDocumentsRoute,
  ShellFinancialsRoute: ShellFinancialsRoute,
  ShellMembersRoute: ShellMembersRouteWithChildren,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSearchRoute: ShellSearchRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellStaffRoute: ShellStaffRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MemberRouteChildren {
  MemberAssistanceRoute: typeof MemberAssistanceRoute
  MemberContributionsRoute: typeof MemberContributionsRoute
  MemberDashboardRoute: typeof MemberDashboardRoute
  MemberProfileRoute: typeof MemberProfileRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAssistanceRoute: MemberAssistanceRoute,
  MemberContributionsRoute: MemberContributionsRoute,
  MemberDashboardRoute: MemberDashboardRoute,
  MemberProfileRoute: MemberProfileRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  MaintenanceRoute: MaintenanceRoute,
  MemberRoute: MemberRouteWithChildren,
  ReceiptIdRoute: ReceiptIdRoute,
  ReportAssistanceRoute: ReportAssistanceRoute,
  ReportCashFlowRoute: ReportCashFlowRoute,
  ReportContributionsRoute: ReportContributionsRoute,
  ReportEventsRoute: ReportEventsRoute,
  ReportFinancialRoute: ReportFinancialRoute,
  ReportMembersRoute: ReportMembersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
